### ISSUE TITLE
Coding style issues.

### ISSUE THREAD

**Issue by MeanEYE** [iliyaM/Ono-academic-test#2]
[Things like these](https://github.com/iliyaM/Ono-academic-test/blob/master/site/templates/home.xml#L217-L224) are a shooting offense. You absolutely need to take care of the way your code looks. You need to make it readable, well commented and properly formatted. You are _NOT_ the only one working in this company and many times someone else will have to go and clean up shit after you or make modifications to a site. If you write like a drunken crab that makes theirs and your life harder.

**You need to write your code as if programmer who works on it after you is a sadist serial killer who knows where you live!**

[This coding style guide](https://github.com/Way2CU/Caracal/blob/develop/docs/coding_style.markdown) is for PHP and Python, but it helps with everything. I'll write XML and CSS soon so you guys can keep up with it.

**Comment by iliyaM** [comment]
drunken crab lol
totally missed this huge gap in the code :(
for the most part is it ok? or is it totally shitty?

**Comment by MeanEYE** [comment]
Not totally shitty but shitty. Good progress through. Much better than
expected.

My concern is what will happen when you tackle big project. Grouping code
and keeping it simple is hard and needed.

**Comment by iliyaM** [comment]
i dont know i have a lot of concerns myself 
i hope ill be fine

**Comment by MeanEYE** [comment]
Correct problems and move on. Everyone's code is bad in the beginning.
